name: send-tweet

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  tweet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm i
      - name: Check if ENV_FILE secret is available
        run: |
          if [ -z "${{ secrets.ENV_FILE }}" ]; then
            echo "ENV_FILE secret is missing!"
            exit 1
          fi
      - run: echo "${{ secrets.ENV_FILE }}" > .env
      - run: node index.js
